name: Run metric recipe bot

on:
  schedule:
    - cron: "44 */1 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run main
      run: |
        python src/main.py
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_PASS: ${{ secrets.REDDIT_PASS }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}